# Generated by Django 3.2.6 on 2021-08-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Organización')),
                ('sigla', models.CharField(max_length=50, unique=True, verbose_name='Sigla Organización')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Organización')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contacto')),
                ('twitter', models.URLField(blank=True, max_length=254, null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, max_length=254, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, max_length=254, null=True, verbose_name='Instagram')),
                ('alcance', models.ManyToManyField(blank=True, to='mantenedores.Alcance')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.comuna')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.pais')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.region')),
            ],
            options={
                'verbose_name': 'Organización Profile',
                'verbose_name_plural': 'Organizaciones Profiles',
            },
        ),
    ]
