# Generated by Django 3.2.6 on 2022-05-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_norma', models.CharField(help_text='Categoría de la norma', max_length=100, unique=True, verbose_name='Categoría de Norma')),
                ('descripcion_cat_norma', models.TextField(blank=True, help_text='Descripción categoría de norma', null=True, verbose_name='Descripción de la categoría de norma')),
                ('icono_categoria', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Categoría Norma')),
            ],
            options={
                'verbose_name': 'Categoría Normas',
                'verbose_name_plural': 'Categorías Normas',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_org_norma', models.CharField(help_text='Nombre web de la organización', max_length=255, verbose_name='Nombre Organización')),
                ('logo_org_norma', models.ImageField(blank=True, help_text='Logo', null=True, upload_to='fotos_constituyentes/', verbose_name='Logo de la Organización')),
                ('descripcion_org_norma', models.TextField(blank=True, help_text='Descripción organización', null=True, verbose_name='Descripción de la Organización')),
                ('sitioweb', models.URLField(blank=True, help_text='URL de la organización', null=True, verbose_name='Sitio Web de la Organización')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='TagNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_norma', models.CharField(help_text='Tag de la norma', max_length=100, unique=True, verbose_name='Tag de Norma')),
                ('descripcion_tag_norma', models.TextField(blank=True, help_text='Descripción tag de norma', null=True, verbose_name='Descripción de tag de norma')),
                ('icono_tag', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Sello Norma')),
            ],
            options={
                'verbose_name': 'Tag Norma',
                'verbose_name_plural': 'Tag Normas',
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oficial_norma', models.CharField(help_text='Título oficial de la norma', max_length=256, verbose_name='Título oficial de norma')),
                ('titulo_web_norma', models.CharField(help_text='Título oficial de la norma', max_length=256, verbose_name='Título web de la norma')),
                ('resumen_norma', models.TextField(help_text='Resumen de la norma', verbose_name='Resumen de la norma')),
                ('url', models.URLField(blank=True, help_text='URL de la Norma', null=True, verbose_name='URL de la Norma')),
                ('importancia_para_chile', models.ImageField(blank=True, help_text='¿Cuán importante es este artículo(s) para la calidad de vida de las personas en Chile?', null=True, upload_to='iconostemas/', verbose_name='Importancia para Chile')),
                ('razones_importancia_norma', models.TextField(blank=True, help_text='¿Por qué este artículo(s) tiene la importancia para la calidad de vida que indicaste en la pregunta anterior?', null=True, verbose_name='Razones de importancia de norma')),
                ('mejora_de_cp80', models.ImageField(blank=True, help_text='En el marco de una agenda de justicia social, económica y de derechos humanos: ¿en qué medida la Nueva Constitución mejora respecto de la Constitución actualmente vigente?', null=True, upload_to='iconostemas/', verbose_name='Mejora de constitución anterior')),
                ('razones_mejora_cp80', models.TextField(blank=True, help_text='¿Cómo puedes justificar la opción asignada en la pregunta anterior?', null=True, verbose_name='Razones de mejora de constitución anterior')),
                ('presencia_otros_paises', models.TextField(blank=True, help_text='¿Hay presencia de artículos similares en otros países? Explícanos en qué países y en qué se parecen', null=True, verbose_name='Presencia en otros países')),
                ('historia_norma', models.TextField(blank=True, help_text='¿Cuál es la historia de este artículo en términos de su creación social?', null=True, verbose_name='Historia de la norma')),
                ('mitos_norma', models.TextField(blank=True, help_text='¿Cuáles son los principales mitos asociados al artículo(s) y porqué son mitos?', null=True, verbose_name='Mitos de la norma')),
                ('futurista_norma', models.TextField(blank=True, help_text='Imagina que estamos en 2052: ¿Cómo es tu entorno y la vida de las personas en Chile después de este artículo(s)?', null=True, verbose_name='Futuro de la norma')),
                ('aporte_desarrollo', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta al desarrollo del país?', null=True, verbose_name='Aporte al desarrollo')),
                ('aporte_ddhh_natura', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta al respeto a los derechos humanos y de la naturaleza?', null=True, verbose_name='Aporte DDHH y naturaleza')),
                ('aporte_seguridad', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a la seguridad y certeza de las personas en Chile?', null=True, verbose_name='Aporte seguridad y certeza')),
                ('aporte_igualdad', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a la igualdad entre todas las personas?', null=True, verbose_name='Aporte a la igualdad')),
                ('aporte_innovacion', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a la innovación y sustentabilidad?', null=True, verbose_name='Aporte a la innovación y sustentabilidad')),
                ('aporte_descentralizacion', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a los procesos de descentralización?', null=True, verbose_name='Aporte a la descentralización')),
                ('aporte_contra_corrupcion', models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a los procesos de participación y a la lucha contra la corrupción?', null=True, verbose_name='Aporte contra la corrupción')),
                ('sello_norma', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Imagen/Sello de Norma')),
                ('categoriadelanorma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_eval_norma', to='evaluaciones.categorianorma', verbose_name='Categoría de la norma')),
                ('org_evaluadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion_eval_norma', to='evaluaciones.organizacionnorma', verbose_name='Organización evaluadora')),
                ('tags_norma', models.ManyToManyField(blank=True, related_name='tags_de_norma', to='evaluaciones.TagNorma', verbose_name='Tags/Sellos aplicados a la norma')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
