# Generated by Django 3.2.9 on 2022-05-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_norma', models.CharField(help_text='Categoría de la norma', max_length=100, unique=True, verbose_name='Categoría de Norma')),
                ('descripcion_cat_norma', models.TextField(blank=True, help_text='Descripción categoría de norma', null=True, verbose_name='Descripción de la categoría de norma')),
                ('icono_categoria', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Categoría Norma')),
            ],
            options={
                'verbose_name': 'Categoría Normas',
                'verbose_name_plural': 'Categorías Normas',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_org_norma', models.CharField(help_text='Nombre web de la organización', max_length=255, verbose_name='Nombre Organización')),
                ('logo_org_norma', models.ImageField(blank=True, help_text='Logo', null=True, upload_to='fotos_constituyentes/', verbose_name='Logo de la Organización')),
                ('descripcion_org_norma', models.TextField(blank=True, help_text='Descripción organización', null=True, verbose_name='Descripción de la Organización')),
            ],
        ),
        migrations.CreateModel(
            name='TagNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_norma', models.CharField(help_text='Tag de la norma', max_length=100, unique=True, verbose_name='Tag de Norma')),
                ('descripcion_tag_norma', models.TextField(blank=True, help_text='Descripción tag de norma', null=True, verbose_name='Descripción de tag de norma')),
                ('icono_tag', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Tag Norma')),
            ],
            options={
                'verbose_name': 'Tag Norma',
                'verbose_name_plural': 'Tag Normas',
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oficial_norma', models.TextField(help_text='Título oficial de la norma', unique=True, verbose_name='Título oficial de norma')),
                ('titulo_web_norma', models.CharField(help_text='Título oficial de la norma', max_length=256, unique=True, verbose_name='Título web de la norma')),
                ('resumen_norma', models.TextField(help_text='Resumen de la norma', verbose_name='Resumen de la norma')),
                ('importancia_para_chile', models.IntegerField(blank=True, help_text='¿Cuán importante es este artículo(s) para la calidad de vida de las personas en Chile?', null=True, verbose_name='Importancia para Chile')),
                ('razones_importancia_norma', models.TextField(blank=True, help_text='¿Por qué este artículo(s) tiene la importancia para la calidad de vida que indicaste en la pregunta anterior?', null=True, verbose_name='Razones de importancia de norma')),
                ('mejora_de_cp80', models.IntegerField(blank=True, help_text='En el marco de una agenda de justicia social, económica y de derechos humanos: ¿en qué medida la Nueva Constitución mejora respecto de la Constitución actualmente vigente?', null=True, verbose_name='Mejora de constitución anterior')),
                ('sello_norma', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Sello de Norma')),
                ('categoriadelanorma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion_eval_norma', to='evaluaciones.categorianorma', verbose_name='Organización evaluadora')),
                ('org_evaluadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion_eval_norma', to='evaluaciones.organizacionnorma', verbose_name='Organización evaluadora')),
            ],
        ),
    ]
