# Generated by Django 3.2.9 on 2022-06-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='norma',
            name='titulo_oficial_norma',
            field=models.TextField(help_text='Texto del artículo', verbose_name='Título oficial de norma'),
        ),
    ]
