# Generated by Django 3.2.9 on 2022-05-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='titulo_oficial_norma',
            field=models.TextField(help_text='Título oficial de la norma', verbose_name='Título oficial de norma'),
        ),
        migrations.AlterField(
            model_name='norma',
            name='titulo_web_norma',
            field=models.CharField(help_text='Título oficial de la norma', max_length=256, verbose_name='Título web de la norma'),
        ),
    ]
