# Generated by Django 3.2.9 on 2022-05-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20220523_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacionnorma',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
    ]
