# Generated by Django 3.2.9 on 2022-06-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20220628_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='titulo_oficial_norma',
            field=models.TextField(help_text='Texto del artículo', verbose_name='Texto del artículo'),
        ),
    ]
