# Generated by Django 3.2.9 on 2022-06-22 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20220613_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
