# Generated by Django 3.2.9 on 2022-05-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_alter_organizacionnorma_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='url',
            field=models.URLField(blank=True, help_text='URL de la Norma', null=True, verbose_name='URL de la Norma'),
        ),
        migrations.AddField(
            model_name='organizacionnorma',
            name='sitioweb',
            field=models.URLField(blank=True, help_text='URL de la organización', null=True, verbose_name='Sitio Web de la Organización'),
        ),
    ]
