# Generated by Django 3.2.9 on 2022-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_norma_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='norma',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
