# Generated by Django 3.2.9 on 2022-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_remove_norma_anexo_norma_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='anexo_norma_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Documento del artículo'),
        ),
    ]
