# Generated by Django 3.2.9 on 2022-05-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_auto_20220523_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='tags_norma',
            field=models.ManyToManyField(blank=True, related_name='tags_de_norma', to='evaluaciones.TagNorma', verbose_name='Tags/Sellos aplicados a la norma'),
        ),
    ]
