# Generated by Django 3.2.9 on 2022-05-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_norma_tags_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='categoriadelanorma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_eval_norma', to='evaluaciones.categorianorma', verbose_name='Categoría de la norma'),
        ),
    ]
