# Generated by Django 3.2.9 on 2022-05-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_alter_norma_categoriadelanorma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma',
            options={'verbose_name': 'Norma/Artículo', 'verbose_name_plural': 'Normas/Artículos'},
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_contra_corrupcion',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a los procesos de participación y a la lucha contra la corrupción?', null=True, verbose_name='Aporte contra la corrupción'),
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_ddhh_natura',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta al respeto a los derechos humanos y de la naturaleza?', null=True, verbose_name='Aporte DDHH y naturaleza'),
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_desarrollo',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta al desarrollo del país?', null=True, verbose_name='Aporte al desarrollo'),
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_descentralizacion',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a los procesos de descentralización?', null=True, verbose_name='Aporte a la descentralización'),
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_igualdad',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a la igualdad entre todas las personas?', null=True, verbose_name='Aporte a la igualdad'),
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_innovacion',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a la innovación y sustentabilidad?', null=True, verbose_name='Aporte a la innovación y sustentabilidad'),
        ),
        migrations.AddField(
            model_name='norma',
            name='aporte_seguridad',
            field=models.TextField(blank=True, help_text='¿En qué forma el artículo(s) analizado aporta a la seguridad y certeza de las personas en Chile?', null=True, verbose_name='Aporte seguridad y certeza'),
        ),
        migrations.AddField(
            model_name='norma',
            name='futurista_norma',
            field=models.TextField(blank=True, help_text='Imagina que estamos en 2052: ¿Cómo es tu entorno y la vida de las personas en Chile después de este artículo(s)?', null=True, verbose_name='Futuro de la norma'),
        ),
        migrations.AddField(
            model_name='norma',
            name='historia_norma',
            field=models.TextField(blank=True, help_text='¿Cuál es la historia de este artículo en términos de su creación social?', null=True, verbose_name='Historia de la norma'),
        ),
        migrations.AddField(
            model_name='norma',
            name='mitos_norma',
            field=models.TextField(blank=True, help_text='¿Cuáles son los principales mitos asociados al artículo(s) y porqué son mitos?', null=True, verbose_name='Mitos de la norma'),
        ),
        migrations.AddField(
            model_name='norma',
            name='presencia_otros_paises',
            field=models.TextField(blank=True, help_text='¿Hay presencia de artículos similares en otros países? Explícanos en qué países y en qué se parecen', null=True, verbose_name='Presencia en otros países'),
        ),
        migrations.AddField(
            model_name='norma',
            name='razones_mejora_cp80',
            field=models.TextField(blank=True, help_text='¿Cómo puedes justificar la opción asignada en la pregunta anterior?', null=True, verbose_name='Razones de mejora de constitución anterior'),
        ),
        migrations.AlterField(
            model_name='norma',
            name='sello_norma',
            field=models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Imagen/Sello de Norma'),
        ),
    ]
