# Generated by Django 3.2.9 on 2022-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_auto_20220523_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagnorma',
            name='icono_tag',
            field=models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Sello Norma'),
        ),
    ]
