# Generated by Django 3.2.9 on 2022-05-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_alter_norma_titulo_oficial_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='titulo_oficial_norma',
            field=models.CharField(help_text='Título oficial de la norma', max_length=256, verbose_name='Título oficial de norma'),
        ),
    ]
