# Generated by Django 3.2.9 on 2022-05-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_alter_norma_titulo_oficial_norma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
    ]
