# Generated by Django 3.2.9 on 2022-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0011_alter_norma_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='importancia_para_chile',
            field=models.ImageField(blank=True, help_text='¿Cuán importante es este artículo(s) para la calidad de vida de las personas en Chile?', null=True, upload_to='iconostemas/', verbose_name='Importancia para Chile'),
        ),
        migrations.AlterField(
            model_name='norma',
            name='mejora_de_cp80',
            field=models.ImageField(blank=True, help_text='En el marco de una agenda de justicia social, económica y de derechos humanos: ¿en qué medida la Nueva Constitución mejora respecto de la Constitución actualmente vigente?', null=True, upload_to='iconostemas/', verbose_name='Mejora de constitución anterior'),
        ),
    ]
