from django.urls import path
from . import views
from .views import *


urlpatterns = [
    path('', HomeView.as_view(), name='inicio'),
    path('enconstruccion/', EsperaView.as_view()),
    path('inicio/', HomeView.as_view(), name='inicio'),
    path('quees/', QueesView.as_view(), name='quees'),
    path('preguntasfrecuentes/', PreguntasView.as_view(),
         name='preguntasfrecuentes'),
    path('ensayos/', EnsayosView.as_view(), name='ensayos'),
    path('ensayo-tomouno/', EnsayotomounoView.as_view(), name='ensayo-tomouno'),
    path('ensayo-tomodos/', EnsayotomodosView.as_view(), name='ensayo-tomodos'),
    path('ensayo-tomotres/', EnsayotomotresView.as_view(), name='ensayo-tomotres'),
    path('ensayo-tomocuatro/', EnsayotomocuatroView.as_view(),
         name='ensayo-tomocuatro'),
    path('ensayo-tomocinco/', EnsayotomocincoView.as_view(),
         name='ensayo-tomocinco'),
    path('terminos/', TerminosView.as_view(), name='terminos'),
    path('constitucion-feminista/', Feminista1View.as_view(),
         name='constitucion-feminista'),
    # path('mujeres-y-desc/', Feminista2View.as_view(), name='mujeres-y-desc'),
    # path('mas-que-juanitas-del-mar/', Feminista3View.as_view(), name='mas-que-juanitas-del-mar'),
    path('las-duenas-de-casa-sin-casa/', Feminista4View.as_view(),
         name='las-duenas-de-casa-sin-casa'),
    path('el-rol-de-las-mujeres-indigenas-en-el-desarrollo-social-politico-y-cultural-de-sus-pueblos/', Feminista5View.as_view(),
         name='el-rol-de-las-mujeres-indigenas-en-el-desarrollo-social-politico-y-cultural-de-sus-pueblos'),
    path('la-vision-de-las-mujeres-afrodescencientes/', Feminista6View.as_view(),
         name='la-vision-de-las-mujeres-afrodescencientes'),
    # path('constitucion-feminista/', Feminista7View.as_view(), name='constitucion-feminista'),
    path('derechos-sexuales-y-reproductivos-descentralizados-en-la-nueva-constitucion/', Feminista8View.as_view(),
         name='derechos-sexuales-y-reproductivos-descentralizados-en-la-nueva-constitucion'),
    # path('constitucion-feminista/', Feminista9View.as_view(), name='constitucion-feminista'),
    path('constitucion-con-enfoque-de-desarrollo-territorial/', Feminista10View.as_view(),
         name='constitucion-con-enfoque-de-desarrollo-territorial'),
    path('derecho-al-trabajo-remunerado/', Feminista11View.as_view(),
         name='derecho-al-trabajo-remunerado'),
    path('derechos-sexuales-y-reproductivos-descentralizados-en-la-nueva-constitucion/', Feminista12View.as_view(),
         name='derechos-sexuales-y-reproductivos-descentralizados-en-la-nueva-constitucion'),
    path('salud-y-autonomia-sexual-y-reproductiva/', Feminista13View.as_view(),
         name='salud-y-autonomia-sexual-y-reproductiva'),
    path('educacion-integral-en-sexualidad-en-la-nueva-constitucion/', Feminista14View.as_view(),
         name='educacion-integral-en-sexualidad-en-la-nueva-constitucion'),
    path('educacion-no-sexista/', Feminista15View.as_view(),
         name='educacion-no-sexista'),
    path('el-rol-de-las-mujeres-y-ninas-en-la-gestion-hidrica/', Feminista16View.as_view(),
         name='el-rol-de-las-mujeres-y-ninas-en-la-gestion-hidrica'),
    path('juntas-abortamos/', Feminista17View.as_view(), name='juntas-abortamos'),
    path('la-importancia-de-los-derechos-sexuales-y-reproductivos-y-su-inclusion-en-la-nueva-constitucion/', Feminista18View.as_view(),
         name='la-importancia-de-los-derechos-sexuales-y-reproductivos-y-su-inclusion-en-la-nueva-constitucion'),
    path('el-rol-de-las-mujeres-indigenas-en-el-desarrollo-social-politico-y-cultural-de-sus-pueblos/', Feminista19View.as_view(),
         name='el-rol-de-las-mujeres-indigenas-en-el-desarrollo-social-politico-y-cultural-de-sus-pueblos'),
    path('las-duenas-de-casa-sin-casa/', Feminista20View.as_view(),
         name='las-duenas-de-casa-sin-casa'),
    path('los-desafios-del-proceso-constituyente-para-abordar-la-crisis-de-los-ciudadanos/', Feminista21View.as_view(),
         name='los-desafios-del-proceso-constituyente-para-abordar-la-crisis-de-los-ciudadanos'),
    path('la-vision-de-las-mujeres-afrodescendientes/', Feminista22View.as_view(),
         name='la-vision-de-las-mujeres-afrodescendientes'),
    path('mujeres-de-maya-sawuri-unicas-tejedoras-un-oficio-multigeneracional/', Feminista23View.as_view(),
         name='mujeres-de-maya-sawuri-unicas-tejedoras-un-oficio-multigeneracional'),
    path('mujeres-de-zonas-de-sacrificio-en-resistencia-de-quintero-y-puchuncavi-reflexiones-y-propuestas/', Feminista24View.as_view(),
         name='mujeres-de-zonas-de-sacrificio-en-resistencia-de-quintero-y-puchuncavi-reflexiones-y-propuestas'),
    path('las-mujeres-en-chile/', Feminista25View.as_view(),
         name='las-mujeres-en-chile'),
    path('mujeres-salud-y-patologizacion-del-ciclo-vital/', Feminista26View.as_view(),
         name='mujeres-salud-y-patologizacion-del-ciclo-vital'),
    path('mujeres-y-desc/', Feminista27View.as_view(), name='mujeres-y-desc'),
    path('mujeres-y-migracion/', Feminista28View.as_view(),
         name='mujeres-y-migracion'),
    path('mas-que-juanitas-del-mar/', Feminista29View.as_view(),
         name='mas-que-juanitas-del-mar'),
    path('ninas-adolescentes-y-la-constitucion/', Feminista30View.as_view(),
         name='ninas-adolescentes-y-la-constitucion'),
    path('participar-en-la-vida-cultural-o-participar-para-cambiar-la-cultura/', Feminista31View.as_view(),
         name='participar-en-la-vida-cultural-o-participar-para-cambiar-la-cultura'),
    path('red-de-defensoras-de-los-ddhh-y-el-programa-feminista-por-una-nueva-constitución-en-busqueda-de-la-articulacion-y-vocacion-de-poder-del-movimiento-feminista/', Feminista32View.as_view(),
         name='red-de-defensoras-de-los-ddhh-y-el-programa-feminista-por-una-nueva-constitución-en-busqueda-de-la-articulacion-y-vocacion-de-poder-del-movimiento-feminista'),
    path('reflexiones-a-partir-de-las-experiencias-de-cinco-mujeres-en-la-defensa-de-sus-territorios/', Feminista33View.as_view(),
         name='reflexiones-a-partir-de-las-experiencias-de-cinco-mujeres-en-la-defensa-de-sus-territorios'),
    path('teletrabajo-e-inequidades-de-genero/', Feminista34View.as_view(),
         name='teletrabajo-e-inequidades-de-genero'),
    path('vida-y-aborto-en-torno-a-la-violencia-de-la-penalizacion/', Feminista35View.as_view(),
         name='vida-y-aborto-en-torno-a-la-violencia-de-la-penalizacion'),
    path('nueva-constitucion-ninas-y-adolescentes/', Feminista36View.as_view(),
         name='nueva-constitucion-ninas-y-adolescentes'),
    path('mujeres-y-sistema-judicial/', Feminista37View.as_view(),
         name='mujeres-y-sistema-judicial'),
    path('mapa-constitucional/', MapaconstitucionalView.as_view(),
         name='mapa-constitucional'),
    path('mapa-constitucional-terminos/', MapaconstitucionalterminosView.as_view(),
         name='mapa-constitucional-terminos'),
    path('rol-de-estado/', RoldeestadoView.as_view(), name='rol-de-estado'),
    path('politica-fiscal/', PoliticafiscalView.as_view(), name='politica-fiscal'),
    path('republica-democratica/', RepublicademocraticaView.as_view(),
         name='republica-democratica'),
    path('sistema-de-gobierno/', SistemadegobiernoView.as_view(),
         name='sistema-de-gobierno'),
    path('plurinacionalidad/', PlurinacionalidadView.as_view(),
         name='plurinacionalidad'),
    path('forma-de-estado/', FormadeestadoView.as_view(), name='forma-de-estado'),
    path('control-constitucional/', ControlconstitucionalView.as_view(),
         name='control-constitucional'),
    path('organos-autonomos/', OrganosautonomosView.as_view(),
         name='organos-autonomos'),
    path('fuerzas-armadas-y-policias/', FuerzasarmadasypoliciasView.as_view(),
         name='fuerzas-armadas-y-policias'),
    path('participacion-popular/', ParticipacionpopularView.as_view(),
         name='participacion-popular'),
    path('trabajo-digno/', TrabajodignoView.as_view(), name='trabajo-digno'),
    path('pensiones-y-seguridad-social/', PensionesyseguridadsocialView.as_view(),
         name='pensiones-y-seguridad-social'),
    path('nivel-de-vida-adecuado/', NiveldevidaadecuadoView.as_view(),
         name='nivel-de-vida-adecuado'),
    path('alimentacion/', AlimentacionView.as_view(), name='alimentacion'),
    path('agua/', AguaView.as_view(), name='agua'),
    path('vivienda-adecuada/', ViviendaadecuadaView.as_view(),
         name='vivienda-adecuada'),
    path('salud/', SaludView.as_view(), name='salud'),
    path('educacion/', EducacionView.as_view(), name='educacion'),
    path('cultura/', CulturaView.as_view(), name='cultura'),
    path('ciencia-y-arte/', CienciayarteView.as_view(), name='ciencia-y-arte'),
    path('medio-ambiente-sano/', MedioambientesanoView.as_view(),
         name='medio-ambiente-sano'),
    path('exigibilidad-de-los-derechos/', ExigibilidaddelosderechosView.as_view(),
         name='exigibilidad-de-los-derechos'),
    path('mujeres/', MujeresView.as_view(), name='mujeres'),
    path('lgbti+/', LgbtiView.as_view(), name='lgbti+'),
    path('infancias/', InfanciasView.as_view(), name='infancias'),
    path('pueblos-indigenas/', PueblosindigenasView.as_view(),
         name='pueblos-indigenas'),
    path('personas-con-discapacidad/', PersonascondiscapacidadView.as_view(),
         name='personas-con-discapacidad'),
    path('personas-mayores/', PersonasmayoresView.as_view(),
         name='personas-mayores'),
    path('personas-migrantes/', PersonasmigrantesView.as_view(),
         name='personas-migrantes'),

    path('iniciativa-popular/', IniciativapopularView.as_view(),
         name='iniciativa-popular'),

    path('mujeres-y-campamentos-en-pandemia/', Feminista38View.as_view(),
         name='mujeres-y-campamentos-en-pandemia'),

    path('debate-constituyente/', DebateconstituyenteView.as_view(),
         name='debate-constituyente'),

    path('cronograma-constitucional/', CronogramaconstitucionalView.as_view(),
         name='cronograma-constitucional'),

    path('glosario-constitucional/', views.GlosarioconstitucionalView.as_view(),
         name='glosario-constitucional'),

    path('reimaginala/', ReimaginalaView.as_view(),
         name='reimaginala'),

]
