# Generated by Django 3.2.6 on 2021-08-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteConstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_constitucion', models.CharField(help_text='Componente Constitucional de Propuesta', max_length=100, unique=True, verbose_name='Componente Constitucional')),
            ],
            options={
                'verbose_name': 'Componente Constitucional',
                'verbose_name_plural': 'Componentes Constitucionales',
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tema_extra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tema complementario')),
                ('problema', models.TextField(blank=True, null=True, verbose_name='Descripción de problema a solucionar')),
                ('situacion', models.TextField(blank=True, null=True, verbose_name='Situación ideal de solución')),
                ('componente', models.TextField(blank=True, null=True, verbose_name='Componente de la Constitución')),
                ('otras_organizaciones', models.BooleanField(default=False, verbose_name='Junto a otras organizaciones')),
                ('organizaciones_de_propuesta', models.TextField(blank=True, null=True, verbose_name='Otras Organizaciones')),
                ('compromiso_convencionales', models.BooleanField(default=False, verbose_name='Convencionales comprometidos')),
                ('anexo_propuesta', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Anexos de la Propuesta')),
                ('anexo2_propuesta', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Otros anexos de la Propuesta-1')),
                ('anexo3_propuesta', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Otros anexos de la Propuesta-2')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Título Propuesta')),
            ],
            options={
                'verbose_name': 'Propuesta Ciudadana',
                'verbose_name_plural': 'Propuestas Ciudadanas',
            },
        ),
        migrations.CreateModel(
            name='TemaPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_propuesta', models.CharField(help_text='Temas predefinidos de propuestas', max_length=100, unique=True, verbose_name='Tema de Propuesta')),
                ('icono_tema', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Temas Propuestas')),
            ],
            options={
                'verbose_name': 'Tema Propuestas',
                'verbose_name_plural': 'Temas Propuestas',
            },
        ),
    ]
