# Generated by Django 3.2.6 on 2021-08-16 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propuestas', '0001_initial'),
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('convencionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor@ de Propuesta'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comuna_propuesta', to='mantenedores.comuna', verbose_name='Comuna de Propuesta'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='convencionales_comprometidos',
            field=models.ManyToManyField(blank=True, related_name='convencionales_comprometidos', to='convencionales.Constituyente', verbose_name='Nombres Convencionales Comprometidos'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='otros_temas',
            field=models.ManyToManyField(blank=True, related_name='otros_temas_propuesta', to='propuestas.TemaPropuesta', verbose_name='Otros Temas de Propuesta'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pais_propuesta', to='mantenedores.pais', verbose_name='País de Origen de Propuesta'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_propuesta', to='mantenedores.region', verbose_name='Región de Propuesta'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propuestas.temapropuesta'),
        ),
    ]
