# Generated by Django 3.2.6 on 2021-08-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='session_hash',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='stage',
        ),
    ]
