# Generated by Django 3.2.6 on 2021-08-20 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propuestas', '0004_auto_20210819_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='compromisos',
            field=models.ManyToManyField(related_name='compromisos_propuestas', through='propuestas.CompromisoPropuesta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='link_extra1',
            field=models.URLField(blank=True, help_text='Ingresa la URL así: https://www.link.com', null=True, verbose_name='Link a información complementaria -2-'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='link_extra2',
            field=models.URLField(blank=True, help_text='Ingresa la URL así: https://www.link.com', null=True, verbose_name='Link a información complementaria -1-'),
        ),
    ]
