# Generated by Django 3.2.6 on 2021-09-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0002_auto_20210907_1811'),
        ('propuestas', '0006_auto_20210830_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='componente',
            field=models.TextField(null=True, verbose_name='Componente de la Constitución'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='otros_temas',
            field=models.ManyToManyField(related_name='otros_temas_propuesta', to='propuestas.SubtemaPropuesta', verbose_name='Otros Temas de Propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pais_propuesta', to='mantenedores.pais', verbose_name='País de Origen de Propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='problema',
            field=models.TextField(null=True, verbose_name='Descripción de problema a solucionar'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='situacion',
            field=models.TextField(null=True, verbose_name='Situación ideal de solución'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='tema_extra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tema complementario'),
        ),
    ]
