# Generated by Django 3.2.6 on 2021-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210909_1346'),
        ('propuestas', '0008_remove_propuesta_convencionales_comprometidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='organizaciones',
            field=models.ManyToManyField(blank=True, related_name='organizaciones_propuesta', to='usuarios.Organizacion', verbose_name='Otras Organizaciones de la Propuesta'),
        ),
    ]
