# Generated by Django 3.2.9 on 2022-05-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convencionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'verbose_name': 'Colectivo', 'verbose_name_plural': 'Colectivos'},
        ),
        migrations.AlterField(
            model_name='lista',
            name='nombre',
            field=models.CharField(max_length=220, unique=True, verbose_name='Nombre Colectivo'),
        ),
    ]
