# Generated by Django 3.2.6 on 2021-08-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='alcance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.alcance'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.comuna'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='descripcion',
            field=models.TextField(default='null', help_text='Este es la reseña oficial de la Organización y se usará en el perfil público', verbose_name='Reseña de la Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='facebook',
            field=models.URLField(default='null', help_text='Ingresa la dirección de tu perfil así: https://www.facebook.com/miorganizacion. Quedará publicado en el perfil público.', verbose_name='Facebook de la Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='instagram',
            field=models.URLField(default='null', help_text='Ingresa la dirección de tu perfil así: https://www.instagram.com/miorganizacion. Quedará publicado en el perfil público.', verbose_name='Instagram de la Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='linkedin',
            field=models.URLField(default='null', help_text='Ingresa la dirección de tu perfil así: https://www.instagram.com/miorganizacion. Quedará publicado en el perfil público.', verbose_name='LinkedIn de la Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='logo_organizacion',
            field=models.ImageField(default='null', help_text='Si deseas subir una imagen o logo representativo de tu organización al perfil público, lo puedes cargar acá', upload_to='', verbose_name='Logo/Imagen de la Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='nombre_contacto',
            field=models.CharField(default='null', help_text='Este nombre de contacto no será difundido públicamente', max_length=255, verbose_name='Nombre Contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='nombre_organizacion',
            field=models.TextField(default='null', help_text='Este es el nombre oficial de la Organización y se usará en el perfil público', verbose_name='Nombre Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.pais'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.region'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='sitioweb',
            field=models.URLField(default='null', help_text='Ingresa la dirección de tu sitio así: https://www.organizacion.com. Quedará publicado en el perfil público.', verbose_name='Sitio Web de la Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='twitter',
            field=models.URLField(default='null', help_text='Ingresa la dirección de tu perfil así: https://www.twitter.com/miorganizacion. Quedará publicado en el perfil público.', verbose_name='Twitter de la Organización'),
            preserve_default=False,
        ),
    ]
