# Generated by Django 3.2.6 on 2021-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210817_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='cualquiercosa',
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Este es la reseña oficial de la Organización y se usará en el perfil público', null=True, verbose_name='Reseña de la Organización'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='No será difundido públicamente', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='facebook',
            field=models.URLField(blank=True, help_text='Ingresa la dirección de tu perfil así: https://www.facebook.com/miorganizacion. Quedará publicado en el perfil público.', null=True, verbose_name='Facebook de la Organización'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='instagram',
            field=models.URLField(blank=True, help_text='Ingresa la dirección de tu perfil así: https://www.instagram.com/miorganizacion. Quedará publicado en el perfil público.', null=True, verbose_name='Instagram de la Organización'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Ingresa la dirección de tu perfil así: https://www.instagram.com/miorganizacion. Quedará publicado en el perfil público.', null=True, verbose_name='LinkedIn de la Organización'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='logo_organizacion',
            field=models.ImageField(blank=True, help_text='Si deseas subir una imagen o logo representativo de tu organización al perfil público, lo puedes cargar acá', null=True, upload_to='', verbose_name='Logo/Imagen de la Organización'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre_contacto',
            field=models.CharField(blank=True, help_text='Este nombre de contacto no será difundido públicamente', max_length=255, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='sitioweb',
            field=models.URLField(blank=True, help_text='Ingresa la dirección de tu sitio así: https://www.organizacion.com. Quedará publicado en el perfil público.', null=True, verbose_name='Sitio Web de la Organización'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='No será difundido públicamente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='twitter',
            field=models.URLField(blank=True, help_text='Ingresa la dirección de tu perfil así: https://www.twitter.com/miorganizacion. Quedará publicado en el perfil público.', null=True, verbose_name='Twitter de la Organización'),
        ),
    ]
