# Generated by Django 3.2.6 on 2021-08-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210818_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='nombre_organizacion',
        ),
    ]
