# Generated by Django 3.2.6 on 2021-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210823_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='convencional',
            name='reservado',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='null', max_length=100, verbose_name='Reservado'),
            preserve_default=False,
        ),
    ]
