# Generated by Django 3.2.6 on 2021-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_convencional_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convencional',
            name='linkedin',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='Linkedin'),
        ),
    ]
