# Generated by Django 3.2.6 on 2021-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_convencional_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='cualquiercosa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convencional',
            name='cualquiercosa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
