# Generated by Django 3.2.6 on 2021-09-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210825_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='logo_organizacion',
            field=models.ImageField(blank=True, help_text='Si deseas subir una imagen o logo representativo de tu organización al perfil público, lo puedes cargar acá', null=True, upload_to='fotos_constituyentes/', verbose_name='Logo/Imagen de la Organización'),
        ),
    ]
