# Generated by Django 3.2.6 on 2021-09-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0002_auto_20210907_1811'),
        ('usuarios', '0010_alter_organizacion_logo_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='alcance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.alcance'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.comuna'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.pais'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.region'),
        ),
    ]
