# Generated by Django 3.2.9 on 2022-07-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNormaInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_norma_int', models.CharField(help_text='Categoría de la norma', max_length=100, unique=True, verbose_name='Categoría de Norma Int')),
                ('descripcion_cat_norma_int', models.TextField(blank=True, help_text='Descripción categoría de norma', null=True, verbose_name='Descripción de la categoría de norma Int')),
                ('icono_categoria_int', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Categoría Norma Int')),
            ],
            options={
                'verbose_name': 'Categoría Normas Int',
                'verbose_name_plural': 'Categorías Normas Int',
            },
        ),
        migrations.CreateModel(
            name='EvaluadoraNormaInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eval_norma_int', models.CharField(help_text='Nombre evaluador@ internacional', max_length=255, verbose_name='Nombre Evaluador@ Internacional')),
                ('logo_org_eval_norma_int', models.ImageField(blank=True, help_text='Logo', null=True, upload_to='fotos_constituyentes/', verbose_name='Logo de la Evaluador@')),
                ('descripcion_eval_norma_int', models.TextField(blank=True, help_text='Descripción de la evaluador@', null=True, verbose_name='Descripción de la Evaluador@')),
                ('sitioweb_eval_norma_int', models.URLField(blank=True, help_text='URL de la eval', null=True, verbose_name='Sitio Web de la Eval')),
            ],
            options={
                'verbose_name': 'Evaluador@',
                'verbose_name_plural': 'Evaluador@s',
            },
        ),
        migrations.CreateModel(
            name='TagNormaInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_norma_int', models.CharField(help_text='Tag de la norma', max_length=100, unique=True, verbose_name='Tag de Norma Int')),
                ('descripcion_tag_norma_int', models.TextField(blank=True, help_text='Descripción tag de norma', null=True, verbose_name='Descripción de tag de norma Int')),
                ('icono_tag_int', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Ícono Sello Norma Int')),
            ],
            options={
                'verbose_name': 'Tag Norma Int',
                'verbose_name_plural': 'Tag Normas Int',
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_oficial_norma_int', models.TextField(blank=True, help_text='Texto oficial de la norma', null=True, verbose_name='Texto oficial de norma')),
                ('titulo_web_norma_int', models.CharField(help_text='Título oficial de la norma', max_length=256, verbose_name='Título web de la norma')),
                ('resumen_norma_int', models.TextField(blank=True, help_text='Resumen de la norma', null=True, verbose_name='Resumen de la norma')),
                ('url_int', models.URLField(blank=True, help_text='URL de la Norma', null=True, verbose_name='URL de la Norma')),
                ('estandares_int', models.ImageField(blank=True, help_text='Según tu experiencia, ¿qué tan alineado está este artículo con los estándares internacionales o las prácticas de tu disciplina?', null=True, upload_to='iconostemas/', verbose_name='Estándares Internacionales')),
                ('constituciones_int', models.ImageField(blank=True, help_text='Según tu experiencia, ¿qué tan alineado está este artículo con los estándares establecidos por otras constituciones alrededor del mundo?', null=True, upload_to='iconostemas/', verbose_name='Constituciones Internacionales')),
                ('explicacion_int', models.TextField(blank=True, help_text='¿Podrías compartir algunas ideas en respaldo de tus respuestas anteriores?', null=True, verbose_name='Explicación Evaluación')),
                ('mensaje_int', models.TextField(blank=True, help_text='¿Qué mensaje darías a las personas en Chile teniendo en cuenta que en septiembre votarán en el plebiscito en favor o rechazo de la nueva propuesta constitucional?', null=True, verbose_name='Mensaje')),
                ('anexo_norma_pdf_int', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Documento del artículo')),
                ('anexo_norma_png_int', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Ilustración del artículo')),
                ('sello_norma_int', models.ImageField(blank=True, null=True, upload_to='iconostemas/', verbose_name='Imagen/Sello de Norma')),
                ('categoriadelanorma_int', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_eval_norma_int', to='evaluacionesinternacionales.categorianormaint', verbose_name='Categoría de la norma')),
                ('org_evaluadora_int', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion_eval_norma_int', to='evaluacionesinternacionales.evaluadoranormaint', verbose_name='Organización evaluadora')),
                ('tags_norma_int', models.ManyToManyField(blank=True, related_name='tags_de_norma_int', to='evaluacionesinternacionales.TagNormaInt', verbose_name='Tags/Sellos aplicados a la norma')),
            ],
            options={
                'verbose_name': 'Artículo Int',
                'verbose_name_plural': 'Artículos Int',
            },
        ),
    ]
