# Generated by Django 3.2.9 on 2022-07-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionesinternacionales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Norma',
            new_name='NormaInt',
        ),
    ]
